name: E2E Testing (Self-Hosted) with Flyway and Playwright Integration Testing
on:
  ###Triggers the workflow on push or pull request events but only for the "master" branch
   push:
    branches:
      - master
env:
  # Enable this for additional debug logging
  ACTIONS_RUNNER_DEBUG: true 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  flyway-initalise-db:
    name: flyway initialise db
    runs-on: self-hosted
    steps:
      # Runs the Flyway Clean command against the Build database
      - name: initialise db
        run: |
          cd 'C:\flyway-9.15.2\'
          flyway info
          flyway clean
          flyway migrate


  integration-test:
    name: playwright e2e test
    runs-on: self-hosted
    needs: flyway-initalise-db
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Install Playwright
        run: |
          npx playwright install

      - name: Run your tests
        working-directory: ./client/src
        run: npx playwright test E2E.spec.js --reporter=html 

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: client/playwright-report
